name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Install Localstack CLI
      run: pip install localstack

    - name: Start Localstack
      run: localstack start -d

    - name: Wait for Localstack to be ready
      run: >
        until curl -s http://localhost:4566/health | grep '"s3": "running"';
        do
          echo "Waiting for Localstack to be ready...";
          sleep 5;
        done

    - name: Debug Localstack
      run: |
        echo "Localstack containers:"
        docker ps -a
        echo "Localstack logs:"
        docker logs $(docker ps -q --filter ancestor=localstack/localstack)

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
